### ISSUE TITLE
OpenPlatformController.php中events 还缺少 component_verify_ticket

### ISSUE THREAD

**Issue by waney** [overtrue/laravel-wechat#101]
/src/Controllers/OpenPlatformController.php

1、推送component_verify_ticket	出于安全考虑，在第三方平台创建审核通过后，微信服务器每隔10分钟会向第三方的消息接收地址推送一次component_verify_ticket，用于获取第三方平台接口调用凭据。

报错：
```
[2017-04-27 19:05:21] local.ERROR: BadMethodCallException: Method [handle] does not exist. in /vendor/laravel/framework/src/Illuminate/Routing/Controller.php:82
Stack trace:
#0 [internal function]: Illuminate\Routing\Controller->__call('handle', Array)
#1 /vendor/overtrue/wechat/src/OpenPlatform/Guard.php(136): call_user_func_array(Array, Array)
#2 /vendor/overtrue/wechat/src/OpenPlatform/Guard.php(111): EasyWeChat\OpenPlatform\Guard->handleEventMessage(Object(EasyWeChat\Support\Collection))
```

**Comment by mingyoung** [comment]
composer update一下就好。
component_verify_ticket event 暂时不处理
