### ISSUE TITLE
Undefined index: action {"exception":"[object] (ErrorException(code: 0): Undefined index: action at vendor/overtrue/laravel-wechat/src/ServiceProvider.php:75)

### ISSUE THREAD

**Issue by oknixus** [overtrue/laravel-wechat#249]
php版本7.1.14
Laravel 5.5
overtrue/wechat (4.0.25)
overtrue/laravel-wechat (4.0.22)

安装后，在执行php artisan的时候，报错：
```
[2018-05-31 10:16:15] local.ERROR: Undefined index: action {"exception":"[object] (ErrorException(code: 0): Undefined index: action at vendor/overtrue/laravel-wechat/src/ServiceProvider.php:75)
[stacktrace]
#0 vendor/overtrue/laravel-wechat/src/ServiceProvider.php(75): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Do...', 75, Array)
#1 vendor/laravel/framework/src/Illuminate/Routing/Router.php(389): Overtrue\\LaravelWeChat\\ServiceProvider->Overtrue\\LaravelWeChat\\{closure}(Object(Illuminate\\Routing\\Router))
#2 vendor/laravel/framework/src/Illuminate/Routing/Router.php(349): Illuminate\\Routing\\Router->loadRoutes(Object(Closure))
#3 vendor/overtrue/laravel-wechat/src/ServiceProvider.php(76): Illuminate\\Routing\\Router->group(Array, Object(Closure))
#4 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Overtrue\\LaravelWeChat\\ServiceProvider->register()
#5 vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Overtrue\\LaravelWeChat\\ServiceProvider))
#6 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load(Array)
#7 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#8 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#9 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#10 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#11 artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 {main}
"}
```
根据这个错误，追踪到是因为`config/wechat.php`配置文件中，因为是公众号，所以在公众号的配置信息中，是没有`action`为索引的数组元素的；`config/wechat.php`的`open_platform`中没有`action`
```
    'route' => [
        /*
         * 是否开启路由
         */
        'enabled' => false,

        /*
         * 开放平台第三方平台路由配置
         */
        'open_platform' => [
            'uri' => 'serve',

            'attributes' => [
                'prefix' => 'open-platform',
                'middleware' => null,
            ],
        ],
    ],
```
然后remove了整个扩展，手动删除`config/wechat.php`之后，再重新`require overtrue/laravel-wechat`才OK！
不知道这个算不算bug，也没想到好的解决办法。
如果`composer install`的时候，覆盖掉了旧的config文件，配置信息就没了，但是如果不覆盖，就会出现上面那个错误

**Comment by overtrue** [comment]
@oknixus OK, 估计是后来的同学添加了配置没有兼容到之前的版本。@mingyoung

**Comment by overtrue** [comment]
@mingyoung https://github.com/overtrue/laravel-wechat/blob/master/src/ServiceProvider.php#L75
