### ISSUE TITLE
Laravel 7 升级到 >= 5.0.8 后 Oauth 中间件报错

### ISSUE THREAD

**Issue by bolechen** [overtrue/laravel-wechat#394]
报错信息如下，回滚到 5.0.7 后则正常：

```
[2020-09-16 20:19:57] testing.ERROR: Trying to get property 'headers' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'headers' of non-object at /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:186)
[stacktrace]
#0 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(186): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/Volumes/Dev/yo...', 186, Array)
#1 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(79): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->addCookieToResponse(Object(Illuminate\\Http\\Request), 'https://open.we...')
#2 /Users/avenger/.composer/vendor/illuminate/support/helpers.php(422): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->Illuminate\\Foundation\\Http\\Middleware\\{closure}('https://open.we...')
#3 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(81): tap('https://open.we...', Object(Closure))
#4 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#5 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#6 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#9 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#17 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#18 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#19 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#20 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Volumes/Dev/youzan-social-app/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Volumes/Dev/youzan-social-app/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Volumes/Dev/youzan-social-app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#38 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(508): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#39 /Volumes/Dev/youzan-social-app/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(292): Illuminate\\Foundation\\Testing\\TestCase->call('GET', 'https://youzan....', Array, Array, Array, Array)
#40 /Volumes/Dev/youzan-social-app/tests/Feature/PosterTest.php(46): Illuminate\\Foundation\\Testing\\TestCase->get('https://youzan....')
#41 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1533): Tests\\Feature\\PosterTest->test_share_url_can_open()
#42 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1139): PHPUnit\\Framework\\TestCase->runTest()
#43 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/Framework/TestResult.php(730): PHPUnit\\Framework\\TestCase->runBare()
#44 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/Framework/TestCase.php(880): PHPUnit\\Framework\\TestResult->run(Object(Tests\\Feature\\PosterTest))
#45 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))
#46 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#47 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#48 /Volumes/Dev/youzan-social-app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(671): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#49 /Users/avenger/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(147): PHPUnit\\TextUI\\TestRunner->run(Object(PHPUnit\\Framework\\TestSuite), Array, Array, true)
#50 /Users/avenger/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit\\TextUI\\Command->run(Array, true)
#51 /Users/avenger/.composer/vendor/phpunit/phpunit/phpunit(61): PHPUnit\\TextUI\\Command::main()
#52 {main}
"} 
```

**Comment by bolechen** [comment]
上面描述不够准确，上面的错误信息只有当 `overtrue/laravel-wechat` >= 5.0.8 且 `overtrue/wechat` >= 5.0 的时候才会出现，5.0.7 的依赖版本好像是 `overtrue/wechat:4.x`，用 `composer update` 升级的时候，自动把 `overtrue/wechat` 升级到 5.x 了。

```
  - Updating overtrue/socialite (2.0.19 => 3.0.3): Loading from cache
  - Updating overtrue/wechat (4.2.35 => 5.0.9): Loading from cache
```

**Comment by overtrue** [comment]
fixed #395
