### ISSUE TITLE
开放平台的服务端验证: Argument #1 ($payload) must be of type array, EasyWeChat\OpenPlatform\Message given

### ISSUE THREAD

**Issue by waney** [overtrue/laravel-wechat#442]
laravel-wechat 7.0.2
w7corp/easywechat 6.3.1

```
[2022-03-31 14:10:17] production.ERROR: Overtrue\LaravelWeChat\Events\OpenPlatform\OpenPlatformEvent::__construct(): Argument #1 ($payload) must be of type array, EasyWeChat\OpenPlatform\Message given, called in vendor/overtrue/laravel-wechat/src/Traits/HandleOpenPlatformServerEvents.php on line 39 {"exception":"[object] (TypeError(code: 0): Overtrue\\LaravelWeChat\\Events\\OpenPlatform\\OpenPlatformEvent::__construct(): Argument #1 ($payload) must be of type array, EasyWeChat\\OpenPlatform\\Message given, called in vendor/overtrue/laravel-wechat/src/Traits/HandleOpenPlatformServerEvents.php on line 39 at vendor/overtrue/laravel-wechat/src/Events/OpenPlatform/OpenPlatformEvent.php:7)
[stacktrace]
#0 vendor/overtrue/laravel-wechat/src/Traits/HandleOpenPlatformServerEvents.php(39): Overtrue\\LaravelWeChat\\Events\\OpenPlatform\\OpenPlatformEvent->__construct()
#1 vendor/w7corp/easywechat/src/OpenPlatform/Server.php(116): App\\Http\\Controllers\\OpenPlatformController->Overtrue\\LaravelWeChat\\Traits\\{closure}()
#2 vendor/w7corp/easywechat/src/Kernel/Traits/InteractWithHandlers.php(173): EasyWeChat\\OpenPlatform\\Server->EasyWeChat\\OpenPlatform\\{closure}()
#3 vendor/w7corp/easywechat/src/OpenPlatform/Server.php(91): EasyWeChat\\OpenPlatform\\Server->EasyWeChat\\Kernel\\Traits\\{closure}()
#4 vendor/w7corp/easywechat/src/Kernel/Traits/InteractWithHandlers.php(173): EasyWeChat\\OpenPlatform\\Server->EasyWeChat\\OpenPlatform\\{closure}()
#5 vendor/w7corp/easywechat/src/OpenPlatform/Server.php(79): EasyWeChat\\OpenPlatform\\Server->EasyWeChat\\Kernel\\Traits\\{closure}()
#6 vendor/w7corp/easywechat/src/Kernel/Traits/InteractWithHandlers.php(173): EasyWeChat\\OpenPlatform\\Server->EasyWeChat\\OpenPlatform\\{closure}()
#7 vendor/w7corp/easywechat/src/OpenPlatform/Server.php(67): EasyWeChat\\OpenPlatform\\Server->EasyWeChat\\Kernel\\Traits\\{closure}()
#8 vendor/w7corp/easywechat/src/Kernel/Traits/InteractWithHandlers.php(173): EasyWeChat\\OpenPlatform\\Server->EasyWeChat\\OpenPlatform\\{closure}()
```

```
namespace App\Http\Controllers;

use EasyWeChat\OpenPlatform\Application;
use Overtrue\LaravelWeChat\Traits\HandleOpenPlatformServerEvents;

class OpenPlatformController extends Controller
{
    use HandleOpenPlatformServerEvents;
    
    public function __invoke(Application $application): \Psr\Http\Message\ResponseInterface
    {
        $app = app('easywechat.open_platform');
        return $this->handleServerEvents($app);
    }
}
```

**Comment by overtrue** [comment]
试试新版
