### ISSUE TITLE
微信url认证报错 ，是不是不支持laravel5.4

### ISSUE THREAD

**Issue by 569616226** [overtrue/laravel-wechat#90]
BadRequestException in Guard.php line 344:

```
in Guard.php line 344
at Guard->getMessage() in Guard.php line 370
at Guard->handleRequest() in Guard.php line 157
at Guard->serve() in WechatController.php line 29
at WechatController->serve()
at call_user_func_array(array(object(WechatController), 'serve'), array()) in Controller.php line 55
at Controller->callAction('serve', array()) in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(WechatController), 'serve') in Route.php line 204
at Route->runController() in Route.php line 160
at Route->run() in Router.php line 559
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Router.php line 561
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 520
at Router->dispatchToRoute(object(Request)) in Router.php line 498
at Router->dispatch(object(Request)) in Kernel.php line 174
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Kernel.php line 149
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
at Kernel->handle(object(Request)) in index.php line 56
```

**Comment by ac1982** [comment]
我最少有3个服务是基于Laravel 5.4和Laravel-wechat部署的，所以是一定支持5.4的。
你的问题，我曾经遇到过，原因是，你在Controller或者Middleware中调用了wechat相关的方法。当一个请求不是微信发起的时候，就会出现你上诉的错误。
从错误类的名称，你也大概可以想到原因，然后从自己的控制器、中间件当中去寻找问题。
`BadRequestException in Guard.php line 344:`

**Comment by 569616226** [comment]
原来是这样的，虽然报错，但是URL还是认证通过了。

**Comment by 569616226** [comment]
问题还是没有解决，有安大神能不能指点一下。 @overtrue

**Comment by overtrue** [comment]
@569616226 我就想问你一句，你 issue 的时候为啥不按规定的模板来？为啥要清空然后粘贴一段错误不带任何上下文与描述？

**Comment by 569616226** [comment]
//路由
`Route::any('/wechat', 'WechatController@serve');`

//控制器
  
public function serve()
    {
        Log::info('request arrived.'); # 注意：Log 为 Laravel 组件，所以它记的日志去 Laravel 日志看，而不是 EasyWeChat 日志

        $wechat = app('wechat');

        $wechat->server->setMessageHandler(function($message){
            echo "您好！欢迎关注我!";
        });

        Log::info('return response.');

        return $wechat->server->serve();
    }
```

访问地址 http://wx.elinkport.cn/wechat报上面的错误，但是微信token认证又通过了。
laravel 日志
[2017-04-05 05:33:01] local.INFO: request arrived.  
[2017-04-05 05:33:01] local.INFO: return response.  
[2017-04-05 05:33:19] local.INFO: request arrived.  
[2017-04-05 05:33:19] local.INFO: return response.  
[2017-04-05 05:33:19] local.ERROR: exception 'EasyWeChat\Server\BadRequestException' with message 'Invalid request.' in /yjdata/www/dhwechat/vendor/overtrue/wechat/src/Server/Guard.php:344
Stack trace:
#0 /yjdata/www/dhwechat/vendor/overtrue/wechat/src/Server/Guard.php(370): EasyWeChat\Server\Guard->getMessage()
#1 /yjdata/www/dhwechat/vendor/overtrue/wechat/src/Server/Guard.php(157): EasyWeChat\Server\Guard->handleRequest()
#2 /yjdata/www/dhwechat/app/Http/Controllers/WechatController.php(27): EasyWeChat\Server\Guard->serve()
#3 [internal function]: App\Http\Controllers\WechatController->serve()
#4 /yjdata/www/dhwechat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#5 /yjdata/www/dhwechat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('serve', Array)
#6 /yjdata/www/dhwechat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\WechatController), Object(Illuminate\Routing\Route), 'serve')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
```

**Comment by overtrue** [comment]
能给我一个你为啥要用浏览器访问那个地址的理由么？

**Comment by 569616226** [comment]
好吧！我知道但是微信服务器的，公众号上也有报错误。但是不知道错误在哪里，所以去直接访问发现有错误以为和这个错误有关系。还是就是按照大神你写的coding上用WEBHOOK自动部署代码入发现用http://proj.dhkty.cc/deploy测试的时候会报http 500的问题，直接用服务器ip去测试又可以通。

**Comment by overtrue** [comment]
有错误就看日志就好了，关于 webhook 的问题你自己去解决，不在这个问题讨论范围内。

**Comment by overtrue** [comment]
@569616226 你代码里的 echo 是谁教你的？

```php
$wechat->server->setMessageHandler(function($message){
            echo "您好！欢迎关注我!";
        });
```

**Comment by overtrue** [comment]
@569616226 你从哪里得到  echo 这个写法的？？？？？？？？

**Comment by 569616226** [comment]
好吧。多谢大神。那个是我打错。

**Comment by overtrue** [comment]
呵呵
